"""Canonical domain model — entities, enums, schemas, errors, and selectors.

All public symbols are re-exported for convenient imports:
    from binary_analysis.domain import Address, Project, Function, ...
"""

from __future__ import annotations

from binary_analysis.domain.entities import (
    Address,
    AuditEvent,
    BasicBlock,
    Binary,
    CallGraph,
    Capability,
    Diagnostic,
    EntryPoint,
    Export,
    Function,
    Heuristic,
    Import,
    Inference,
    Instruction,
    Observation,
    Project,
    Reference,
    Report,
    Section,
    String,
    Symbol,
    Unknown,
)
from binary_analysis.domain.enums import (
    AuditResult,
    Confidence,
    DiagnosticSeverity,
    Endianness,
    ExitCode,
    FunctionNameSource,
    ImportResolution,
    ProjectState,
    ReferenceKind,
    ReportType,
)
from binary_analysis.domain.errors import (
    AmbiguousSelectorError,
    AnalysisFailedError,
    BackendFailureError,
    BinaryAnalysisError,
    BinaryNotFoundError,
    DependencyMissingError,
    EntityNotFoundError,
    ImportFailedError,
    InvalidArgsError,
    InvalidConfigError,
    OperationTimeoutError,
    ProjectNotFoundError,
    UnsupportedFormatError,
    error_type_for,
    fail,
)
from binary_analysis.domain.schemas import (
    canonical_address,
    deserialize_address,
    entity_to_dict,
    safe_json_dumps,
    serialize_address,
    serialize_enum,
)
from binary_analysis.domain.selectors import (
    ParsedSelector,
    ResolvedEntity,
    format_candidates,
    parse_selector,
    resolve_function,
    resolve_functions,
)

__all__ = [
    "Address",
    "AmbiguousSelectorError",
    "AnalysisFailedError",
    "AuditEvent",
    "AuditResult",
    "BackendFailureError",
    "BasicBlock",
    "Binary",
    "BinaryAnalysisError",
    "BinaryNotFoundError",
    "CallGraph",
    "Capability",
    "Confidence",
    "DependencyMissingError",
    "Diagnostic",
    "DiagnosticSeverity",
    "Endianness",
    "EntityNotFoundError",
    "EntryPoint",
    "ExitCode",
    "Export",
    "Function",
    "FunctionNameSource",
    "Heuristic",
    "Import",
    "ImportFailedError",
    "ImportResolution",
    "Inference",
    "Instruction",
    "InvalidArgsError",
    "InvalidConfigError",
    "Observation",
    "OperationTimeoutError",
    "ParsedSelector",
    "Project",
    "ProjectNotFoundError",
    "ProjectState",
    "Reference",
    "ReferenceKind",
    "Report",
    "ReportType",
    "ResolvedEntity",
    "Section",
    "String",
    "Symbol",
    "Unknown",
    "UnsupportedFormatError",
    "canonical_address",
    "deserialize_address",
    "entity_to_dict",
    "error_type_for",
    "fail",
    "format_candidates",
    "parse_selector",
    "resolve_function",
    "resolve_functions",
    "safe_json_dumps",
    "serialize_address",
    "serialize_enum",
]
